### PR TITLE
Committing support version for Kentico-11

### PR DESCRIPTION
**Pull request by sultanwork77**
What I have done is looked through all the modules I could and all the one's that have V10 as their latest Supported Version then I have added to V11 else I have ignored. 

The list of modules I did look into are all submitted in the other branch Support_V11

Thanks
Sultan

### CODE REVIEW

**Comment by sultanwork77** [comment]
@petrsvihlik  @ChristopherJennings  Any update on this so this. So that we can go ahead an use it.

**Comment by petrsvihlik** [comment]
@sultanwork77 could you please make sure all tests are passing? https://ci.appveyor.com/project/kentico/kinspector/build/1.0.394/tests the CI is failing because of that

**Comment by ChristopherJennings** [comment]
Aside from the test that isn't passing and one other small issue with the class definition module (#167), this looks like it is working as essentially the same in v11 as it does in v10. At a minimum, we need the test to be updated to make sure it passes (it's not expecting the versions that are being reported because you added v11). I've created a new issue for the class definition module issue (#167) as this is a minor issue and can be addressed later if needed, but we'd certainly like to address it now if possible.

**Comment by sultanwork77** [comment]
@petrsvihlik 
I have updated those and all tests are passed now.

**Comment by sultanwork77** [comment]
@ChristopherJennings 
Can I know what's need's to be done to fix #167 , I will see if I can do that as well depending on the buffer I have.

**Comment by ChristopherJennings** [comment]
Thanks for this PR! @sultanwork77, I'll update #167 with some additional details. If you plan to tackle it or have questions, just make a comment there.

**Pull request merged**
