### PR TITLE
Display module description separately from running the module

### PR DESCRIPTION
**Pull request by WakeflyCBass**
…he module

Currently, in order to see the details of what a module does, you have to Load the Module, executing its behavior. This is problematic because first-time users won't have the context of what the modules do in order to know which module they want to run. This commit adds a button "Show Comments" that displays the comments separately from the results. In order to do this without also displaying the "results", I had to remove the Results toggle from the header bar, and place it directly on the Toggle arrow and the Header text. No other changes to existing functionality were needed.

### CODE REVIEW

**Comment by ondrejsevcik** [comment]
Hi @WakeflyCBass,

this is awesome. I really like it. 

I was thinking if it's good to display module description all the time (even when the module is run). What do you think? 

cc: @petrsvihlik 

screenshot:
screenshot

**Comment by WakeflyCBass** [comment]
So, you're suggesting that we just always show the module description, rather than having it shown via a button?
I'm not a fan of that - I like the conciseness of the one-line-per-module interface on page-load, and how it means each module is evenly spaced out for looking for a specific module. 
But I do think it's important to be able to view the descriptions without running the module.

As to whether to show the description every time you run the module, whether you've clicked "show comments" or not, I'm fine either way, no preference. I think having them be separate is nice since it takes up slightly less room if you're just running a module you run often, and already know how it works.

**Comment by ChristopherJennings** [comment]
I think what @ondrejsevcik means is that the comments should always show if the module was run. So in the end the functionality would be: toggle the comments is the module is collapsed, but show comment if the module is expanded/run.

**Comment by WakeflyCBass** [comment]
That'd be the second paragraph of my comment, then. Easy enough to set up - I'd just hide the show/hide button on running of the module, and show the module. @ondrejsevcik - Let me know if after my comment above, you still think that's the best way forward.

**Comment by petrsvihlik** [comment]
@ondrejsevcik @ChristopherJennings I agree, I'd always show the comments.

I like this feature very much. I think it will be very helpful, especially in combination with:
 https://github.com/Kentico/KInspector/pull/115. ping @JosefDvorak

**Comment by WakeflyCBass** [comment]
@petrsvihlik @ondrejsevcik @ChristopherJennings Alright, I'll set it up that way now.

**Comment by ondrejsevcik** [comment]
What I meant is that description is visible all the time. But what @WakeflyCBass is writing makes sense. Users who know what the module is doing will appreciate more compact variant without description.

What do you think @petrsvihlik, @ChristopherJennings ?

(BTW: we have a 'comment' in the code but it's actually 'description' of the module)

**Comment by petrsvihlik** [comment]
@ondrejsevcik : The modules should be collapsed by default with an option of expanding the description (`comment` property) before running the module. Once it has been run the description should still be visible. Which is in other words the same as @ChristopherJennings was sayig.

**Comment by petrsvihlik** [comment]
@WakeflyCBass The "Show comments" button doesn't work for me in Chrome...it works in FF though.

**Comment by WakeflyCBass** [comment]
@petrsvihlik What's the best way of going about that? That change involved making the onclick be part of the text and arrow, instead of the encompassing div - I'm not quite sure how I'd change that when the module runs. Maybe make a copy of the method, and pass in parameters - and if it doesn't match, do nothing - then put the method in both places?

**Comment by WakeflyCBass** [comment]
Done.

**Comment by petrsvihlik** [comment]
Brilliant! Merged! Thanks @WakeflyCBass!

**Pull request merged**
