### PR TITLE
Added module to check password policy settings

### LINKED ISSUE #17: Check for password policy/encrtyption
This is a simple task that is meant to be picked up by newcomers. Check out http://www.firsttimersonly.com/.

Steps to be taken:
- [fork the repository](https://help.github.com/articles/fork-a-repo/)
- clone it to your local machine, you can use [Visual Studio](http://www.malgreve.net/2014/06/17/cloning-getting-code-from-git-repository-to-visual-studio/), [GitHub desktop](https://help.github.com/desktop/guides/contributing/cloning-a-repository-from-github-desktop/) or [command line](https://help.github.com/articles/cloning-a-repository/)
  - we recommend using [GitHub extension for Visual Studio](https://visualstudio.github.com/)
- open your local clone with Visual Studio
- [create a new module](https://github.com/Kentico/KInspector/wiki/Writing-a-custom-module)
- implement the **logic** which consists of 2 checks:
  - check whether the `CMSUsePasswordPolicy` keys in the `CMS_SettingsKey` table are set to `true`. if not, return `ModuleResults` with status Warning (see [documentation](https://docs.kentico.com/display/K82/Password+strength+policy+and+its+enforcement))
  - check whether the `CMSPasswordFormat` key in the `CMS_SettingsKey` table is set to `SHA2SALT`. if not, return `ModuleResults` with status Error (see [documentation](https://docs.kentico.com/display/K82/Password+encryption+in+database))
- check whether your code complies with our [contribution guidelines](https://github.com/Kentico/Home/blob/master/CONTRIBUTING.md)
- push your changes to your fork (VS->Team Explorer->Changes->Commit&Sync)
- create a PR and include Fixes #17 in the message

We'll review the change and either merge right away it or suggest potential changes.
If you have any questions feel free to ask in the repository chat [Join the chat at https://gitter.im/Kentico/KInspector](https://gitter.im/Kentico/KInspector?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

### PR DESCRIPTION
**Pull request by martbrow**
Fixes #17

### CODE REVIEW

**Comment by ondrejsevcik** [comment]
Hi @martbrow, thank you for your contribution. 
Is this final solution or you will work on it further? I'm a little bit confused because of the 'Initial commit' sentence in your commit message.

**Comment by ondrejsevcik** [comment]
I just reviewed your code and apart from a few findings I mentioned above, it looks really good :+1:

**Comment by martbrow** [comment]
Hi Ondrej,

I've made the changes suggested - I look forward to your feedback.

**Comment by petrsvihlik** [comment]
Looks good, thank you, Martin!

**Comment by ondrejsevcik** [comment]
I just realized that the ```CMSUsePasswordPolicy``` setting is site specific. Take a look at this screenshot https://i.imgur.com/XxAwi31.png.

We don't count with it in a code. We need to 

- Check for every ```CMSUsePasswordPolicy``` value 
- Maybe it would be good to display also SiteName along with KeyName and KeyValue

**Comment by petrsvihlik** [comment]
Yeah, I didn't realize that either. I've reopened the issue #17

**Pull request merged**
