### PR TITLE
Add detection of users with plaintext passwords

### LINKED ISSUE #22: Plaintext passwords
Even if the setting ```Password format``` is set to any other value than ```plaintext```, some of the passwords in the database could be still in the plaintext format.

This module should display a list of users where password format is set to ```plaintext```.

### PR DESCRIPTION
**Pull request by rowdypixel**
Fixes #22.Shows a list of users with plaintext passwords.

### CODE REVIEW

**Comment by ondrejsevcik** [comment]
Hi Dan, thanks for the contribution. Before we merge your code, we need to adjust a few things.
- if the password uses ```plaintext``` format, the value in the database record is set to empty string.
- the description is too generic
    - Could you please describe why it is bad to have plaintext passwords and what they can do about it? You can point them for the further explanation to the [documentation]( https://docs.kentico.com/display/K82/Password+encryption+in+database).

**Comment by rowdypixel** [comment]
Thanks for the feedback. 

Could you let me know where you would like the documentation to be placed? I have been looking at other modules and pull requests and don't see a clear place where it belongs.

**Comment by ondrejsevcik** [comment]
We will try to improve documentation in the upcoming weeks. You can place it right into the comment property. Take a look at the [WebPartColumnsModule.cs](https://github.com/Kentico/KInspector/blob/master/KInspector.Modules/Modules/Content/WebPartColumnsModule.cs) for example.

**Comment by rowdypixel** [comment]
Thanks. I have updated the code with a new and improved query and added the documentation into the module.

**Comment by ondrejsevcik** [comment]
Great! Thanks again. I'm pretty sure that our customers and consultants will appreciate this.

**Pull request merged**
