### PR TITLE
Issue #94

### PR DESCRIPTION
**Pull request by pnmcosta**
Proposed MacroValidator abstraction and implementation of it in the WebPartAnalyzerModule, looking forward to your feedback.

### CODE REVIEW

**Comment by petrsvihlik** [comment]
Thanks for the PR. It seems to work fine.
I had a look in the code and here are my findings:
- there is a code duplication that can be avoided in the following methods:
 - `AnalyseWhereAndOrderByConditionsInPageTemplateWebParts` and `AnalyseWhereAndOrderByConditionsInPageTemplateWebPartsCustomMacros`
 - `AnalysePageTemplateWebParts` and `AnalysePageTemplateWebPartsCustomMacros`
 - the logic can be made more generic and parameterized
- it's not necessary to create an instance of `MacroValidator` in every method (have you thought about having a single instance for the whole class or a singleton similar to `ProjectCodeFilesHelper`?)
- could you also adjust the `TransformationAnalyzerModule` so that it would use the `MacroValidator`? It would make it clear whether the logic is generic enough.
- could you please unify the line spacing and XML comments in the classes (`MacroValidator` & `WebPartAnalyzerModule`) so that it's in line with other classes? (have a look at e.g. `ProjectCodeFilesHelper`)

I'll be glad to accept the PR when the above is resolved.

**Comment by pnmcosta** [comment]
HI @petrsvihlik,

Done.

- used 2 args for the errors one for the standard and the other for the deprecated methods, hope that's what you meant with parameterized ;)
- done, sorry missed that on the initial version, all ammended
- done, but just for MacroValidator.Current.ContainsPotentialXss do you think we should also check for deprecated macro methods here? how do you propose this to be reported? seperately or just as it is (issue in transformation, go to code)?
- tried to, hope I haven't missed anything, can you elaborate? What are the VS2015 settings?

But I think I messed my fork, I did a commit directly to my master branch see https://github.com/pnmcosta/KInspector/tree/7dbadb48a7eb42ad60cb3a2a817dc748a4cc4e81 then I noticed that there was an "Update branch" in this pull request, and incorrectly assumed it would pick my changes on my fork and update the Pull request, seems to have done the opposite! 

My changes are still there, but can you help update the Pull request from this state? Or should I just create a new pull request?

Thanks,
P.

**Comment by pnmcosta** [comment]
oh never mind! seems to be ok.. https://github.com/Kentico/KInspector/pull/95/commits but can you please confirm I've done the right thing? thanks.

**Comment by petrsvihlik** [comment]
1. Not exactly. I'd add a `MacroValidator.MacroType` parameter to the method and call it twice. That way there would be no code duplication. Regarding the `MacroValidator.Current.CheckForCustomMacros` check, you can perform it only once outside the method.
2. ok
3. 

> do you think we should also check for deprecated macro methods here? 

yes, that's what i had in my mind. I think there should be a method similar to `AnalyseXss` that would use the `MacroValidator` to perform the checks. Going one step further, we could make the logic in the `AnalyseXss`  more generic to reuse the part in the `if (potentialXssFound)` block.
Actually `ContainsPotentialXss` doesn't seem to be related to macros at all so we should put it back where it was.
4. there is still some rome for improvement :) we put:
 - one line between a (end)region and a method
 - two lines between methods (or any members)
 - two lines between regions
 - also make sure all XML comments are present (e.g. `AnalyseWhereAndOrderByConditionsInPageTemplateWebParts` is missing comments for `pageTemplateName` and other parameters)

let me know if it makes sense

**Comment by pnmcosta** [comment]
- I see, yes makes it much cleaner, thanks - done
- done, sorry assumed incorrectly that XSS could be a check by the MacroValidator, rolled back and added a separate check (and report) for custom macros only as instructed.
- done, please let me know if I may have missed something.

**Comment by petrsvihlik** [comment]
looks fine now! thank you for the contribution, good job!

**Comment by pnmcosta** [comment]
awesome, thank you, glad to be of help (and learn a few things in the process) :+1:

**Pull request merged**
