### PR TITLE
Resolves #123 - Update modules that can support V10

### LINKED ISSUE #123: Enable compatible modules for Kentico 10
- test modules against K10
- enable those that work
- adjust those that don't (or create new issues if fixes require more effort)

pseudo code of what needs to be done:

```
clone the repository
for each (module in https://github.com/Kentico/KInspector/tree/master/KInspector.Modules)
{
  add new Version("10.0") to SupportedVersions array
  if(module returns correct data)
  {
    leave the supported version in
  }
  else
  {
    try
    {
      fix the module while not breaking it for older versions
    }
    catch
    {
       remove "10" from the supported versions array
       create new issues in this repository if the fix requires more effort
    }
  }
}
commit the changes

```

### PR DESCRIPTION
**Pull request by ileshmistry**
Resolves #123.

### CODE REVIEW

**Comment by ChristopherJennings** [comment]
@ileshmistry, thanks for the PR for these. This is a really important bit of work and I certainly appreciate your help with this! Please let me know when you are ready for review of this and I'll take a look. 

One thing i did notice is that, as of aef3020, the build is failing one of the (very few tests) we have in place. You might already be aware of this, but I figured I'd mention it.

**Comment by ileshmistry** [comment]
@ChristopherJennings I have made a small update for the test for the password policy, hopefully this has fixed this?

**Comment by ileshmistry** [comment]
@ChristopherJennings I need to quickly go into a meeting, but can speak after that and I can explain what I have and haven't had time to do. Would this be ok?

**Comment by ChristopherJennings** [comment]
@ileshmistry, if possible, let's keep the discussion here in the thread. That way there's an open dialog that others can follow if they need to.

**Comment by ileshmistry** [comment]
@ChristopherJennings sure that makes perfect sense. 

What I have done is looked through all the modules I could and all the one's that have V9 as their latest Supported Version. So any that had V9 missing, I didn't update to V10, as I think we should make them available for V9 as well. 

The list of modules I did look into are all submitted in the other branch V10-upgrade. 

The other area I didn't want to change my DB on were the Instance Setup modules. I can change them to V10, but wouldn't be able to test. Do you want me to push them or better not to? 

I hope this is all ok.

Thanks
Ilesh

**Comment by ChristopherJennings** [comment]
I agree that targeting only the modules with V9 support is a good place to start, as that should address the bulk of the useful modules. I don't see a V10-branch on your GitHub. Did you push that up or am I missing something? Also, I noticed that all you did was add the version to each of the modules and update that one test. Was there really no other changes necessary or are those change on the V10-upgrade branch you mentioned? 

We can handle the setup modules in another issue/pull-request. 

I'll try to pull this down and review it tomorrow. Hopefully, it'll be good to merge and I can just bring it in.

**Comment by ileshmistry** [comment]
@ChristopherJennings Yep that was the starting point to add the V10 support in. 
https://github.com/ileshmistry/KInspector/tree/v10-upgrade

**Comment by ileshmistry** [comment]
@ChristopherJennings we also need to look at the documentation references, as some still point to V8 documentation. Maybe making them non-version specific might help? Or point to the latest version?

**Comment by ChristopherJennings** [comment]
The documentation links is a separate issue I think and I've created an issues for this. I'm going to pull this down and review it today.

**Comment by ChristopherJennings** [comment]
I also added a commit (82bdcce669bb3e18cbfe1f1fea8b60e710302f02) directly after to enable/fix the setup modules.

**Pull request merged**
