### PR TITLE
Fix #161

### LINKED ISSUE #161: PasswordPolicyModule.cs should check for the PBKDF2 format in K10
Kentico 10 introduced a new password hashing algorithm PBKDF2. SHA2SALT is no longer recommended.

See: https://docs.kentico.com/k10/securing-websites/designing-secure-websites/securing-user-accounts-and-passwords/setting-the-user-password-format

### PR DESCRIPTION
**Pull request by djjach**
It fix the issue reported #161 . In this pull request I updated this module to work with version 11 also the unit test

### CODE REVIEW

**Comment by ChristopherJennings** [comment]
Thanks for the PR @djjach, I'll try to take a look later today.

**Comment by djjach** [comment]
I missed to fix SecuritySettingsModule.sql, there is a setting CMSPasswordFormat it display SHA2SALT as recommended value it should be depended on current Kentico version.

**Comment by djjach** [comment]
Fixed security settings CMSPasswordFormat

**Comment by ChristopherJennings** [comment]
@djjach Thanks for the PR, I finally had a chance to do the review on this and pulled it in.

**Pull request merged**
